name: CI testing - complete

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

jobs:
  check-diff:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/focus-diff.yml

  pytest:
    runs-on: ${{ matrix.os }}
    needs: check-diff
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: ["3.7", "3.8", "3.10"]
        requires: ['oldest', 'latest']
        exclude:
          - {python-version: "3.7", requires: 'latest'}
          - {python-version: "3.10", requires: 'oldest'}
    env:
      PYTEST_ARTEFACT: test-results-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}.xml
      PYTORCH_URL: https://download.pytorch.org/whl/cpu/torch_stable.html

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    # seems that MacOS jobs take much more than orger OS
    timeout-minutes: 95

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Github Actions: Run step on specific OS: https://stackoverflow.com/a/57948488/4521646
    - name: Setup macOS
      if: runner.os == 'macOS'
      run: |
        # https://github.com/pytorch/pytorch/issues/20030
        brew install gcc libomp ffmpeg openblas
    - name: Setup Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt update --fix-missing
        sudo apt install -y ffmpeg
    - name: Setup Windows
      if: runner.os == 'windows'
      run: |
        choco install ffmpeg

    - uses: ./.github/actions/caching
      with:
        os: ${{ runner.os }}
        requires: ${{ matrix.requires }}
        python-version: ${{ matrix.python-version }}

    - name: Freeze PIL (hotfix)
      run: |
        # import of PILLOW_VERSION which they recently removed in v9.0 in favor of __version__
        pip install -q "Pillow<9.0"  # It messes with torchvision

    - name: Install base dependencies
      run: |
        pip --version
        pip install --requirement requirements.txt --upgrade --find-links $PYTORCH_URL

    - name: Install all dependencies
      run: |
        python ./requirements/adjust-versions.py requirements.txt
        python ./requirements/adjust-versions.py requirements/image.txt
        pip install --requirement requirements/devel.txt --upgrade --find-links $PYTORCH_URL
        pip install --force-reinstall pypesq
        pip list

    - name: Tests
      env:
        TEST_DIRS: "${{ needs.check-diff.outputs.test-dirs }}"
      run: |
        phmdoctest README.md --outfile tests/test_readme.py
        python -m pytest torchmetrics $TEST_DIRS --cov=torchmetrics --junitxml="junit/$PYTEST_ARTEFACT" --durations=50

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: $PYTEST_ARTEFACT
        path: "junit/$PYTEST_ARTEFACT"
      if: failure()

    - name: Statistics
      if: success()
      run: |
        coverage xml
        coverage report

    - run: echo "::set-output name=TORCH::$(python -c 'import torch ; print(torch.__version__)' 2>&1)"
      id: info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: cpu,pytest,${{ runner.os }},python${{ matrix.python-version }},torch${{ steps.info.outputs.TORCH }}
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
